# Generated by Django 3.1.6 on 2021-12-05 04:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('photo_main', models.ImageField(default=False, upload_to='photos/%Y%m%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y%m%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y%m%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y%m%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y%m%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y%m%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%Y%m%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('added_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
