# Generated by Django 3.1.4 on 2021-12-23 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('pro_name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('nature', models.CharField(blank=True, max_length=200, null=True)),
                ('unit', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('per_mg', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('available', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('buyer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('pro_name', models.CharField(blank=True, max_length=200, null=True)),
                ('unit', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('isPending', models.BooleanField(default=False)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('transactedAt', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('driver_name', models.CharField(blank=True, max_length=200, null=True)),
                ('pro_name', models.CharField(blank=True, max_length=200, null=True)),
                ('unit', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('isDelivered', models.BooleanField(default=False)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('num_plate', models.CharField(blank=True, max_length=200, null=True)),
                ('colour', models.CharField(blank=True, max_length=200, null=True)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('car', models.CharField(blank=True, max_length=200, null=True)),
                ('arrivedAt', models.DateTimeField(null=True)),
                ('delivery_location', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.CharField(blank=True, max_length=200, null=True)),
                ('orderedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('order_ID', models.CharField(blank=True, max_length=200, null=True)),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.stock')),
            ],
        ),
    ]
