# Generated by Django 3.1.4 on 2021-12-24 11:05

import datetime
from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card_type', models.CharField(choices=[('NHIS', 'NHIS'), ('PASS', 'PASSPORT'), ('VOTE', 'VOTERS ID CARD')], default='VOTE', max_length=4)),
                ('secondPhoneNumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('id_number', models.CharField(max_length=50)),
                ('profile_photo', models.ImageField(blank=True, upload_to='photos/%Y%m%d/')),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='Company name')),
                ('company_type', models.CharField(choices=[('LTD', 'Limited Liability'), ('PTN', 'Partnership'), ('soleprop', 'Sole Proprietorship')], default='LTD', max_length=50)),
                ('registration_number', models.CharField(blank=True, max_length=20)),
                ('vat', models.CharField(blank=True, max_length=50, verbose_name='VAT')),
                ('tin', models.CharField(blank=True, max_length=50, verbose_name='TIN')),
                ('registration_certificate', models.FileField(blank=True, upload_to='documents/')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('region', models.CharField(blank=True, max_length=200)),
                ('town_or_city', models.CharField(blank=True, max_length=20)),
                ('address_1', models.CharField(blank=True, max_length=50)),
                ('address_2', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
