# Generated by Django 3.1.4 on 2021-12-23 13:05

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='account',
            name='id_card_type',
            field=models.CharField(choices=[('NHIS', 'NHIS'), ('PASS', 'PASSPORT'), ('VOTE', 'VOTERS ID CARD')], default='VOTE', max_length=4),
        ),
        migrations.AddField(
            model_name='account',
            name='id_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='account',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y%m%d/'),
        ),
        migrations.AddField(
            model_name='account',
            name='secondPhoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='account',
            name='user_type',
            field=models.CharField(choices=[('BUY', 'Buyer'), ('SELL', 'Seller')], default='BUY', max_length=4),
        ),
    ]
