# Generated by Django 3.1.4 on 2021-12-23 13:32

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211223_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address_1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='account',
            name='region',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='account',
            name='registration_certificate',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='account',
            name='registration_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='tin',
            field=models.CharField(blank=True, max_length=50, verbose_name='TIN'),
        ),
        migrations.AlterField(
            model_name='account',
            name='town_or_city',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='vat',
            field=models.CharField(blank=True, max_length=50, verbose_name='VAT'),
        ),
    ]
