# Generated by Django 3.1.4 on 2021-12-24 11:05

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211223_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='address_1',
        ),
        migrations.RemoveField(
            model_name='account',
            name='address_2',
        ),
        migrations.RemoveField(
            model_name='account',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='company_type',
        ),
        migrations.RemoveField(
            model_name='account',
            name='country',
        ),
        migrations.RemoveField(
            model_name='account',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='account',
            name='id_card_type',
        ),
        migrations.RemoveField(
            model_name='account',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='account',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='account',
            name='region',
        ),
        migrations.RemoveField(
            model_name='account',
            name='registration_certificate',
        ),
        migrations.RemoveField(
            model_name='account',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='account',
            name='secondPhoneNumber',
        ),
        migrations.RemoveField(
            model_name='account',
            name='tin',
        ),
        migrations.RemoveField(
            model_name='account',
            name='town_or_city',
        ),
        migrations.RemoveField(
            model_name='account',
            name='vat',
        ),
        migrations.AlterField(
            model_name='account',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
